[package]
name = "analyze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
crossbeam-channel = "0.5"
heaptrack-rust-track = { path = "../track" }
serde = "1.0"
timely = "0.12"
