[package]
name = "heaptrack-rust-track"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
backtrace = "0.3"
crossbeam-channel = "0.5"
lazy_static = "1.4"
libc = "0.2"
